Repository ZeroOctave/resource-gallery, pull requests merged in 2023-06, with the labels that each got.

#68 Addition of new Resources on Git.
  src/pages/git.astro
  src/pages/resource.astro
Labels: waiting for review

#81 Added in resources - Blog and website
  src/pages/webdev.astro
Labels: waiting for review

#84 #77 add home in the navbar [GSSOC'23]
  src/components/navbar/navbar.astro
Labels: gssoc23, level1

#95 adding open source programs
  src/pages/opensource/programs.md
Labels: gssoc23, level1

#86 Added icons and links in footer issue #18
  src/components/footer.astro
Labels: waiting for review

#97 Fixed : issue #92
  package-lock.json
  src/components/navbar/navbar.astro
  tailwind.config.cjs
Labels: waiting for review

#101 Fixed : issue 94
  src/pages/about.astro
Labels: gssoc23, level1

#105 Addition of Resources for learning Cybersecurity
  src/pages/cybersecurity.astro
  src/pages/cybersecurity/books.md
  src/pages/cybersecurity/videos.md
  src/pages/resource.astro
Labels: waiting for review

#107 Issue #103 - PR for Navbar Update
  src/components/navbar/navbar.astro
Labels: gssoc23, level2

#115 About page UI issue were resolved.
  src/pages/about.astro
Labels: gssoc23, level2, waiting for review

#116 Add Open Source Programs
  src/pages/opensource/programs.md
Labels: gssoc23, level1

#122 Added the new blog by Parmesh Bhatt
  src/pages/blog/Insights of AWS Marketplace.md
Labels: gssoc23, level3

#166 #165 Issue fixed
  src/components/footer.astro
  src/components/ui/link.astro
Labels: gssoc23, level1
