Repository ZeroOctave/resource-gallery, pull requests merged in 2023-07, with the labels that each got.

#170 added resources
  src/pages/webdev.astro
Labels: gssoc23, level1

#172 add new resources
  src/pages/cloud.astro
  src/pages/resource.astro
Labels: gssoc23, level2, waiting for review, review-done, ready for merge

#212 Remove the additional same blog from the website
  src/pages/blog/Blockchain-And DeFi Technology.md
Labels: bug, gssoc23, level1, waiting for review, review-done, ready for merge

#205 Share functionality added
  src/pages/blog.astro
Labels: enhancement, gssoc23, level2, waiting for review, review-done, ready for merge

#196 Added the resources about the React Hooks and their features by Parmesh Bhatt
  src/pages/blog/A-Complete-Guide-to-React-Hooks-Discover-Their-Features.md
Labels: gssoc23, level1

#223 Added effecting hover effect on the icons
  src/components/footer.astro
  src/components/logos.astro
Labels: gssoc23, level1, waiting for review, review-done, ready for merge

#230 blog added
  src/pages/blog/Understanding Cloud Technology: A Comprehensive Guide.md
  src/pages/blog/src/pages/blog/Low code and no-code tools.md
Labels: gssoc23, level2

#243 Feat: Embeded Newsletter from SubStack
  public/newsletter.png
  src/assets/newsletter.png
  src/components/cta.astro
  src/components/newsletter.astro
  src/pages/index.astro
Labels: enhancement, gssoc23, level2, ready for merge

#237 Add our team section
  package-lock.json
  src/pages/about.astro
  src/pages/blog.astro
Labels: gssoc23, level3, waiting for review

#235 Added blog on the Will AI Replace Humans
  src/pages/blog/will-AI-replace-Humans.md
Labels: gssoc23, level2, 📃Blog Contribution, waiting for review, review-done, ready for merge

#246 Feat: added Ganesh Mourya as maintainer
  src/pages/about.astro
Labels: waiting for review, ready for merge

#191 Added NodeJs and MongoDB Resources
  src/pages/webdev.astro
Labels: gssoc23, level1, waiting for review, ready for merge

#250 fix: Modifications in frameworks.astro , webdev.astro, javascript.astro Files
  src/pages/frameworks.astro
  src/pages/javascript.astro
  src/pages/webdev.astro
Labels: bug, gssoc23, level2, waiting for review, review-done, ready for merge

#236 Added hovers to the cards
  src/components/features.astro
Labels: enhancement, gssoc23, level1, waiting for review, review-done, ready for merge

#262 Added ScrollToTop button
  pnpm-lock.yaml
  src/assets/arrowUp.svg
  src/components/ScrollToTop.astro
  src/pages/index.astro
Labels: enhancement, gssoc23, level1, waiting for review, review-done, ready for merge

#269 #264 new docs Added
  src/pages/frameworks.astro
Labels: gssoc23, level1, waiting for review, review-done, ready for merge

#271 feat: DevDocs.io
  src/pages/webdev.astro
Labels: gssoc23, level1, waiting for review, review-done, ready for merge

#270 feat: javascript.info
  src/pages/javascript.astro
Labels: gssoc23, level1, waiting for review, review-done, ready for merge

#274 Improve the hover and dropdown menu of the navbar
  src/components/navbar/dropdown.astro
  src/components/navbar/navbar.astro
Labels: gssoc23, level1, waiting for review, review-done, ready for merge

#277 Adding DOM manipulation blog post in javascript resources
  src/pages/javascript.astro
Labels: gssoc23, level1, waiting for review, review-done, ready for merge

#275 Added New Article on "How Does JavaScript Work Behind the Scenes?"
  src/pages/javascript.astro
Labels: gssoc23, level1, waiting for review, review-done, ready for merge

#265 search function in blogs
  src/pages/blog.astro
  src/utils/search.js
Labels: gssoc23, level2, waiting for review, review-done

#256 feat: Node.js Dev Doc(Official)
  src/pages/frameworks.astro
Labels: gssoc23, level1, waiting for review, review-done, ready for merge
