Repository ZeroOctave/resource-gallery, pull requests merged in 2023-05, with the labels that each got.

#39 Create CONTRIBUTION.md
  CONTRIBUTION.md
Labels: invalid, gssoc23

#35 Improved the content of cards on resource page
  .gitignore
  src/pages/resource.astro
Labels: gssoc23, fixed

#28 Updated features.astro with hover effects on icons
  src/components/features.astro
Labels: gssoc23

#27 [PR for #20]: Created Templates to add new feature, report bugs and pull requests.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/Pull_Request_Template.md
Labels: gssoc23, level2

#37 Added Blog (JavaScript Top 10 Tips and Tricks)
  src/pages/blog/JavaScript Top 10 Tips & Tricks.md
Labels: gssoc23, level3

#15 Update README.md
  README.md
Labels: level2, waiting for review

#56 Added favicon
  package-lock.json
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-256x256.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  src/assets/android-chrome-192x192.png
  src/assets/android-chrome-512x512.png
  src/assets/apple-touch-icon.png
  src/assets/browserconfig.xml
  src/assets/favicon-16x16.png
  src/assets/favicon-32x32.png
  src/assets/favicon.ico
  src/assets/mstile-150x150.png
  src/assets/safari-pinned-tab.svg
  src/assets/site.webmanifest
  src/layouts/Layout.astro
Labels: gssoc23, level2, waiting for review
